modified:   bash_stuff/bash_aliases 	modified:   screenrc_c

diff --git a/bash_stuff/bash_aliases b/bash_stuff/bash_aliases
--- a/bash_stuff/bash_aliases
+++ b/bash_stuff/bash_aliases
@@ -17,6 +17,9 @@ alias sysinfoarchlogo="sh $HOME/scripts/system/sysinfo.sh"
 alias sysinfoirc="sh $HOME/scripts/system/newsysinfo.sh"
 #alias ssinfo="sh $HOME/scripts/system/ssinfo.sh"
 
+# COLORS - POOF
+alias COLORSPOOF="perl ~/scripts/misc/hypnotoad.pl ; sh ~/scripts/misc/pacman_nom.sh ; archey ; sh ~/scripts/misc/colors.sh"
+
 # User Defined Quick Command Aliases
 ##################
 # reset & source bash_profile
@@ -89,6 +92,9 @@ alias mvnzb="$HOME/scripts/misc/mvnzb.sh"
 #alias mplayeralsa="mplayer -ao alsa "
 alias mplayerlog="mplayer -identify $@> $HOME/.mplayer/mylog.log"
 alias mplayerfb="mplayer -vo fbdev -fbmode qvga -vm -ac mad "
+alias npmplyer="sh ~/scripts/video/nowplaying-mplayer.sh" 
+alias radioson="sh $HOME/scripts/audio/radio-switcher.sh"
+
 # urxvt quick aliases
 alias ashell="urxvt -name 'a' &"
 alias cshell="urxvt -name 'c' &"
@@ -362,9 +368,10 @@ alias tronad="/usr/local/bin/armagetronad"
 #alias idesktool="$HOME/.idesktop/idesktool"
 #alias mediainfohtm="mediainfo --Output=HTML " 
 alias vlcremote="vlc --control lirc "
-alias vlctv="vlc --hdtv-fix --aspect-ratio=16:9 --deinterlace-mode=b --disable-screensaver --control lirc /dev/video0"
-#alias mplayertv="mplayer /dev/video0 -cache 2000 -panscan 1 -vf yadif=1/3,hqdn3d "
-alias mplayertv="mplayer -vo xv /dev/video0 "
+alias vlctv="vlc --hdtv-fix --aspect-ratio=16:9 --deinterlace-mode=b --disable-screensaver --control lirc /dev/video1"
+#alias mplayertv="mplayer /dev/video1 -cache 2000 -panscan 1 -vf yadif=1/3,hqdn3d "
+alias mplayertv="mplayer -vo xv /dev/video1 "
+#alias mplayertv="mplayer /dev/video1 "
 #alias mplayerscrnshot="mplayer -vf -ao null "
 alias weechat="weechat-curses"ALIAS
 # Google MusicManager - Wine
@@ -445,27 +452,120 @@ alias grooveshark-desktop='export GNOME_DESKTOP_SESSION_ID=1 && adobe-air /opt/g
 ##################
 #alias gchrome="wine /opt/windows/Google/chrome/chrome.exe"
 
+# calculator
+calc() { echo "scale=3;$@" | bc -l ; }
+
 # easy extraction
-function extract () {
-   if [ -f $1 ] ; then
-       case $1 in
-           *.tar.bz2)   tar xvjf $1    ;;
-           *.tar.gz)    tar xvzf $1    ;;
-           *.bz2)       bunzip2 $1     ;;
-           *.rar)       unrar x $1     ;;
-           *.gz)        gunzip $1      ;;
-           *.tar)       tar xvf $1     ;;
-           *.tbz2)      tar xvjf $1    ;;
-           *.tgz)       tar xvzf $1    ;;
-           *.zip)       unzip $1       ;;
-           *.Z)         uncompress $1  ;;
-           *.7z)        7z x $1        ;;
-           *)           echo "don't know how to extract '$1'..." ;;
+extract() {
+ local e=0 i c
+ for i; do
+   if [ -f $i && -r $i ]; then
+       c=
+       case $i in
+         *.tar.bz2) c='tar xjf'    ;;
+         *.tar.gz)  c='tar xzf'    ;;
+         *.bz2)     c='bunzip2'    ;;
+         *.gz)      c='gunzip'     ;;
+         *.tar)     c='tar xf'     ;;
+         *.tbz2)    c='tar xjf'    ;;
+         *.tgz)     c='tar xzf'    ;;
+         *.7z)      c='7z x'       ;;
+         *.Z)       c='uncompress' ;;
+         *.exe)     c='cabextract' ;;
+         *.rar)     c='unrar x'    ;;
+         *.xz)      c='unxz'       ;;
+         *.zip)     c='unzip'      ;;
+         *)     echo "$0: cannot extract \`$i': Unrecognized file extension" >&2; e=1 ;;
        esac
+       [ $c ] && command $c "$i"
    else
-       echo "'$1' is not a valid file!"
+       echo "$0: cannot extract \`$i': File is unreadable" >&2; e=2
    fi
- }
+ done
+ return $e
+}
+
+# to-do helper
+todo() {
+   test -f $HOME/.todo || touch $HOME/.todo
+   if test $# = 0
+   then 
+           cat $HOME/.todo
+   elif test $1 = -l
+   then
+           cat -n $HOME/.todo
+   elif test $1 = -c
+   then
+           > $HOME/.todo
+   elif test $1 = -r
+   then
+           cat -n $HOME/.todo
+           echo -ne "----------------------------\nType a number to remove: "
+           read NUMBER
+           sed -ie ${NUMBER}d $HOME/.todo
+   else
+           echo $@ >> $HOME/.todo
+   fi
+}
+
+# note taker
+note ()
+{
+       #if file doesn't exist, create it
+       [ -f $HOME/.notes ] || touch $HOME/.notes
+       #no arguments, print file
+       if [ $# = 0 ]
+       then
+               cat $HOME/.notes
+       #clear file
+       elif [ $1 = -c ]
+       then
+               > $HOME/.notes
+       #add all arguments to file
+       else
+               echo "$@" >> $HOME/.notes
+       fi
+}
+
+# view doc
+docview ()
+{
+  if [ -f $1 ] ; then
+      case $1 in
+          *.pdf)       xpdf $1    ;;
+          *.ps)        oowriter $1    ;;
+          *.odt)       oowriter $1     ;;
+          *.txt)       leafpad $1       ;;
+          *.doc)       oowriter $1      ;;
+          *)           echo "don't know how to extract '$1'..." ;;
+      esac
+  else
+      echo "'$1' is not a valid file!"
+  fi
+}
+
+# kingbash
+## 1
+function kingbash.fn() {
+  echo -n "KingBash> $READLINE_LINE" #Where "KingBash> " looks best if it resembles your PS1, at least in length.
+  OUTPUT=`/usr/bin/kingbash "$(compgen -ab -A function)"`
+  READLINE_POINT=`echo "$OUTPUT" | tail -n 1`
+  READLINE_LINE=`echo "$OUTPUT" | head -n -1`
+  echo -ne "\r\e[2K"; }
+bind -x '"\t":kingbash.fn'
+
+##2
+#kingbash.gb() {
+#    OUTPUT=$(/usr/bin/kingbash.gambas "$READLINE_LINE" "$READLINE_POINT")
+#    READLINE_POINT=$(echo "$OUTPUT"|tail -n1)
+#    READLINE_LINE=$(echo "$OUTPUT"|head -n1)
+#}
+#
+#if  [ "$DISPLAY"  != "" ]; then
+#        #bind -x '"\C-e": kingbash' #Use Ctrl-e
+#        bind -x '"\t": kingbash'        #Use Tab
+#fi
+##
 
 #####################
 ##   End Aliases   ##
